### ISSUE TITLE
Building NumericalChameleon myself

### ISSUE THREAD

**Issue by Mechtilde** [jonelo/n16n-desktop#1]
Hello,

I want to build this program myself. I didn't find any information about dependencies and build system.
Please give me a hint, where I can find these informations.

Kind regards
Mechtilde

**Comment by axkr** [comment]
Additional question: is there a Maven build with dependencies available?
(for example for class jonelo.sugar.util.GeneralString.java)

**Comment by Mechtilde** [comment]
I will be happy to be able to build the two libraries i need. My problem is that I can't find any information about the dependencies to build numerical chameleon.
The source code for  class jonelo.sugar.util.GeneralString.java I found under 
https://github.com/AriseUIC/JackSum/tree/master/src/jonelo/sugar/util
So now I try to build a Debian package from it. 
Regards
Mechtilde

**Comment by axkr** [comment]
I don't need the GUI part, because I want to use the lib on the server side.
Do you provide a Maven JAR without the GUI?

See:
- http://matheclipse.org/input?i=IntegerName%28123007%2C%5C%22German%5C%22%29
- http://matheclipse.org/input?i=RomanNumeral%28%7B1%2C%202%2C%203%2C%204%2C%205%2C%2010%2C%2050%2C%2060%2C%20100%2C%20250%2C%20500%2C%201000%2C%201500%2C%202600%7D%29

**Comment by Mechtilde** [comment]
I packaged sugar as part of jacksum-sugar. This contains the sugar.jar
I did an upload as a Debian package. You can follow the process at
https://ftp-master.debian.org/new.html (NewQueue)
You will see it at the next update round. If it in't there any more after that, you can find it iin the Debian repo n experimental.
Now I start to package phoneticalphabet and spokennumbers as part of the numerical chameleon. This will coming soon at the NewQueue

**Comment by jonelo** [comment]
@Mechtilde apologies for not replying to your request sooner. You find all dependencies at https://numericalchameleon.loefflmann.net/en/legal/copyright.html - and in the source package that is hosted on https://sourceforge.net/projects/numchameleon/ - and if you download and install one of the app packages - see https://numericalchameleon.loefflmann.net/en/download.html - , you always find the dependencies also in the legal/libraries.txt file.

The 1st release of the NC was in 2001 and GitHub simply didn't exist at that time, GitHub went live 2008. Therefore you still find many of its pieces on sf.net including the sourcecode. I understand that it might be a bit confusing and sometimes a hard route to put everything together. I am working on it in order to improve the situation. Please stay tuned.

@axkr For now there is no Maven build available. However, my long term plan is to extract the util classes from the NumericalChameleon and put it in a separate lib in order to support other free software projects more easily.

@Mechtilde and @axkr if you have questions, please fire away.

Kind regards,
Johann

**Comment by Mechtilde** [comment]
Hello Johann,

thanks for your reply

Am 01.06.20 um 12:37 schrieb Johann N. Löfflmann:
> @Mechtilde apologies for not replying to your request sooner. 

> You find all dependencies at https://numericalchameleon.loefflmann.net/en/legal/copyright.html -

This are only the names and there aren't the locations where I can get them.

> and in the source package that is hosted on https://sourceforge.net/projects/numchameleon/ - 

Yes, the source code of numerical chameleon but not the sourcecode of
e.g jacksum

Now I packaged jacksum-sugar and parts of numerical chameleon for
Debian. I will be coming soon there after review.

> I understand that it might be a bit confusing and sometimes a hard route to put everything together. I am working on it in order to improve the situation. Please stay tuned.

The problem was to find the source code of the libraries you use in
numerical chameleon.

> Kind regards,
> Johann

Kind regads

-- 
Mechtilde Stehmann
## Apache OpenOffice
## Freie Office Suite für Linux, MacOSX, Windows und OS/2
## Debian Developer
## PGP encryption welcome
## F0E3 7F3D C87A 4998 2899  39E7 F287 7BBA 141A AD7F

**Comment by jonelo** [comment]
Hello @Mechtilde ,
 
> and in the source package that is hosted on https://sourceforge.net/projects/numchameleon/ -
> Yes, the source code of numerical chameleon but not the sourcecode of e.g jacksum

Let's see ...

```
$ unzip -l nc-3.0.0-src.zip | grep jacksum
   254197  2006-07-30 19:41   jacksum-1.7.0-src.zip
```

here we go. You can get the file from here: https://sourceforge.net/projects/numchameleon/files/NumericalChameleon/3.0.0/

Jacksum has also its own website. You find the source code also there: http://jacksum.net

> Now I packaged jacksum-sugar and parts of numerical chameleon for Debian. I will be coming soon there after review.

Please note that the sugar libs in NC 3 are later than the sugar libs in Jacksum 1.7.

> The problem was to find the source code of the libraries you use in numerical chameleon.

I hope it is not a problem anymore.

```
$ unzip nc-3.0.0-src.zip readme.txt && cat $_
Archive:  nc-3.0.0-src.zip
  inflating: readme.txt

This package contains all sources of all components that are required
to build the NumericalChameleon 3.0.0 from scratch

See also http://NumericalChameleon.net


numericalchameleon-3.0.0-src.zip
   description:       NumericalChameleon 3.0.0, more than an unit converter, a NumericalChameleon
   website:           http://NumericalChameleon.net
   maintenance:       maintained by jonelo (Johann N. Loefflmann)
   license:           GPLv3 or later
   license file:      licenses/gpl-3.0.txt

sugar-300-src.zip
   description:       Sugar 3.0.0, useful java classes
   website:           http://johann.loefflmann.net
   maintenance:       maintained by jonelo
   license:           LGPLv2 or later => compatible with the GPLv3
   license file:      licenses/lgpl-2.1.txt
                      licenses/lgpl-3.0.txt

analogclockbean-1.0.0-src.zip
   description:       AnalogClockBean 1.0.0
   website:           http://www.numericalchameleon.net
   maintenance:       derived from the public domain code from Fred Swartz at leepoint.net,
                      maintenance for the NC by jonelo
   changes:           minor bugfixes only
   license:           3 clause BSD => compatible with the GPLv3
   license file:      licenses/analogclockbean-license.txt

jacksum-1.7.0-src.zip
   description:       Jacksum 1.7.0
   website:           http://jacksum.net
   maintenance:       maintained by jonelo
   license:           GPLv2 or later => compatible with the GPLv3 => GPLv3
   license file:      library licenses/gpl-2.0.txt
                      library licenses/gpl-3.0.txt

jcalendar-1.4-src.zip
   description:       Calendar Bean 1.4
   website:           http://www.toedter.com/jcalendar
   maintenance:       maintained by Kai Toedter
   release:           July 11, 2011
   changes:           none
   license:           LGPLv2 or later => compatible with the GPLv3
   license file:      licenses/lgpl-2.1.txt

nimrodln.jar
   description:       Nimrod Look and Feel 1.2d
   website:           http://nilogonzalez.es/nimrodlf/download-en.html
   maintenance:       maintained by Nilo J. Gonzlez
   base release:      Dec 6, 2015
   changes by jonelo: none
   license:           LGPLv2.1 or later => compatible with the GPLv3
   license file:      library licenses/lgpl-2.1.txt

jcoord-1.1-b2-src.zip
   description:       based on Jcoord 1.1-b
   website:           http://www.jstott.me.uk/jcoord/
   maintenance:       maintained by Jonathan Stott
   base release:      April 3, 2006
   changes:           bugfix in constructor in LatLng.java by jonelo
   license:           GPL v2 or later => GPL v3 or later => compatible with the GPLv3 => GPLv3
   license file:      licenses/gpl-3.0.txt

dice-200801-src.zip
   description:       Dice
   website:           http://www.jdemo.de
   maintenance:       Markus Gebhard, Johann Loefflmann for the dice in the NC
   base release:      January 2008
   changes:           only minor changes by jonelo
   license:           GPL v2 or later => GPL v3 or later => compatible with the GPLv3
   license file:      licenses/gpl-2.0.txt
                      licenses/gpl-3.0.txt

hvjavacal-0.13-src.zip
   description:       calendar 0.13
   website:           http://joyds1.joensuu.fi/calendar/index.html
   maintenance:       mainted by Hannu Vissen, Finland
   base release:      December 21, 2009
   changes:           none
   license:           GPL v2 or later =>GPL v3 or later => compatible with the GPLv3
   license file:      licenses/gpl-2.0.txt
                      icenses/gpl-3.0.txt

jtattoo.jar
   description:       JTattoo 1.6
   website:           http://www.jtattoo.net
   maintenance:       maintained by Michael Hagen, Germany
   changes:           none
   license:           GPL v3
   license file:      library licenses/gpl-3.0.txt
```

Kind regards,
Johann
